### ISSUE TITLE
macOS src/dune paths for C language stub

### ISSUE THREAD

**Issue by ghost** [alan-j-hu/ocaml-oniguruma#1]
Hello,

on a Mac using macports, the paths for -I and -L are missing. Here is my dune file under src/ which solve the issue:

`(library
 (name oniguruma)
 (public_name oniguruma)
 (foreign_stubs (language c) (names onig_stubs) (flags -I/opt/local/include))
 (c_library_flags (-L/opt/local/lib -lonig)))`

**Comment by alan-j-hu** [comment]
Hi, I'm going to try to fix this, but I'm going to need your help so you can test my code on a Mac. So my dune file isn't brittle with hard-coded paths, I'm going to use pkg-config in the build process. First, could you please run `pkg-config oniguruma --libs` and `pkg-config oniguruma --cflags` and tell me what the output is?

**Comment by ghost** [comment]
Hello Alan,

***@***.***:~$ pkg-config oniguruma —libs

-L/opt/local/lib -lonig

***@***.***:~$ pkg-config oniguruma —cflags

-I/opt/local/include


Thanks for your time on this issue!!


> Le 27 août 2021 à 05:09, Alan ***@***.***> a écrit :
> 
> pkg-config oniguruma --libs

--
Philippe Strauss
Strauss Engineering
CH-1273 Arzier
https://www.strauss-engineering.ch
+41 79 302 28 87

**Comment by alan-j-hu** [comment]
Could you please `git checkout` the `build` branch and see if the code compiles now?

**Comment by ghost** [comment]
YES it does build & install fine. Thank you!

***@***.***:~/Sources/Build/ocaml-oniguruma-git$ git checkout build

Branch 'build' set up to track remote branch 'build' from 'origin'.
Switched to a new branch ‘build'

***@***.***:~/Sources/Build/ocaml-oniguruma-git$ dune build @install

          cc src/onig_stubs.o
onig_stubs.c:146:24: warning: initializing 'const OnigUChar *const' (aka 'const unsigned char *const') with an expression of type 'const char *' converts between pointers to integer types with different sign [-Wpointer-sign]
    const UChar* const pattern = String_val(pattern_val);
                       ^         ~~~~~~~~~~~~~~~~~~~~~~~
onig_stubs.c:162:34: warning: passing 'OnigUChar [90]' to parameter of type 'const char *' converts between pointers to integer types with different sign [-Wpointer-sign]
        error = caml_copy_string(err_buf);
                                 ^~~~~~~
/Users/philippe/.opam/ouaibedev/lib/ocaml/caml/alloc.h:39:48: note: passing argument to parameter here
CAMLextern value caml_copy_string (char const *);
                                               ^
onig_stubs.c:204:24: warning: initializing 'const OnigUChar *const' (aka 'const unsigned char *const') with an expression of type 'const char *' converts between pointers to integer types with different sign [-Wpointer-sign]
    const UChar* const string = String_val(string_val);
                       ^        ~~~~~~~~~~~~~~~~~~~~~~
onig_stubs.c:227:55: warning: passing 'OnigUChar [90]' to parameter of type 'const char *' converts between pointers to integer types with different sign [-Wpointer-sign]
        caml_raise_with_string(*ocaml_onig_Error_exn, err_buf);
                                                      ^~~~~~~
/Users/philippe/.opam/ouaibedev/lib/ocaml/caml/fail.h:93:65: note: passing argument to parameter 'msg' here
CAMLextern void caml_raise_with_string (value tag, char const * msg)
                                                                ^
onig_stubs.c:246:24: warning: initializing 'const OnigUChar *const' (aka 'const unsigned char *const') with an expression of type 'const char *' converts between pointers to integer types with different sign [-Wpointer-sign]
    const UChar* const string = String_val(string_val);
                       ^        ~~~~~~~~~~~~~~~~~~~~~~
onig_stubs.c:267:55: warning: passing 'OnigUChar [90]' to parameter of type 'const char *' converts between pointers to integer types with different sign [-Wpointer-sign]
        caml_raise_with_string(*ocaml_onig_Error_exn, err_buf);
                                                      ^~~~~~~
/Users/philippe/.opam/ouaibedev/lib/ocaml/caml/fail.h:93:65: note: passing argument to parameter 'msg' here
CAMLextern void caml_raise_with_string (value tag, char const * msg)
                                                                ^
6 warnings generated.
  ocamlmklib src/dlloniguruma_stubs.so,src/liboniguruma_stubs.a
ld: warning: dylib (/opt/local/lib/libonig.dylib) was built for newer macOS version (11.2) than being linked (11.0)
    ocamlopt src/oniguruma.cmxs
ld: warning: dylib (/opt/local/lib/libonig.dylib) was built for newer macOS version (11.2) than being linked (11.0)

***@***.***:~/Sources/Build/ocaml-oniguruma-git$ dune install

        opam (internal)
[WARNING] var was deprecated in version 2.1 of the opam CLI. Use opam var instead or set OPAMCLI environment variable to 2.0.
Installing /Users/philippe/.opam/ouaibedev/lib/oniguruma/META
Installing /Users/philippe/.opam/ouaibedev/lib/oniguruma/dune-package
Installing /Users/philippe/.opam/ouaibedev/lib/oniguruma/liboniguruma_stubs.a
Installing /Users/philippe/.opam/ouaibedev/lib/oniguruma/oniguruma.a
Installing /Users/philippe/.opam/ouaibedev/lib/oniguruma/oniguruma.cma
Installing /Users/philippe/.opam/ouaibedev/lib/oniguruma/oniguruma.cmi
Installing /Users/philippe/.opam/ouaibedev/lib/oniguruma/oniguruma.cmt
Installing /Users/philippe/.opam/ouaibedev/lib/oniguruma/oniguruma.cmti
Installing /Users/philippe/.opam/ouaibedev/lib/oniguruma/oniguruma.cmx
Installing /Users/philippe/.opam/ouaibedev/lib/oniguruma/oniguruma.cmxa
Installing /Users/philippe/.opam/ouaibedev/lib/oniguruma/oniguruma.ml
Installing /Users/philippe/.opam/ouaibedev/lib/oniguruma/oniguruma.mli
Installing /Users/philippe/.opam/ouaibedev/lib/oniguruma/opam
Installing /Users/philippe/.opam/ouaibedev/lib/oniguruma/oniguruma.cmxs
Deleting /Users/philippe/.opam/ouaibedev/doc/oniguruma/CHANGES.md
Installing /Users/philippe/.opam/ouaibedev/doc/oniguruma/CHANGES.md
Deleting /Users/philippe/.opam/ouaibedev/doc/oniguruma/LICENSE
Installing /Users/philippe/.opam/ouaibedev/doc/oniguruma/LICENSE
Deleting /Users/philippe/.opam/ouaibedev/doc/oniguruma/README.md
Installing /Users/philippe/.opam/ouaibedev/doc/oniguruma/README.md
Deleting /Users/philippe/.opam/ouaibedev/lib/stublibs/dlloniguruma_stubs.so
Installing /Users/philippe/.opam/ouaibedev/lib/stublibs/dlloniguruma_stubs.so
***@***.***:~/Sources/Build/ocaml-oniguruma-git$ 


> Le 27 août 2021 à 17:19, Alan ***@***.***> a écrit :
> 
> 
> Could you please git checkout the build branch and see if the code compiles now?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android. 
> 

--
Philippe Strauss
Strauss Engineering
CH-1273 Arzier
https://www.strauss-engineering.ch
+41 79 302 28 87

**Comment by alan-j-hu** [comment]
Hmm, it seems that the C code gives warnings on your machine, but it doesn't for mine. Could you please checkout to commit `e209ef` and try building again? I want to see if the warnings are due to `const`s I just added.

**Comment by ghost** [comment]
Hi Alan, hmm it’s the same warnings using the e209ef commit

> Le 27 août 2021 à 17:32, Alan ***@***.***> a écrit :
> 
> 
> Hmm, it seems that the C code gives warnings on your machine, but it doesn't for mine. Could you please checkout to commit e209ef and try building again? I want to see if the warnings are due to consts I just added.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android. 
> 

***@***.***:~/Sources/Build/ocaml-oniguruma-git$ git checkout e209ef
Note: switching to 'e209ef'.

***@***.***:~/Sources/Build/ocaml-oniguruma-git$ dune clean
***@***.***:~/Sources/Build/ocaml-oniguruma-git$ dune build @install
          cc src/onig_stubs.o
onig_stubs.c:146:18: warning: initializing 'const OnigUChar *' (aka 'const unsigned char *') with an expression of type 'const char *' converts between pointers to integer types with different sign [-Wpointer-sign]
    const UChar* pattern = String_val(pattern_val);
                 ^         ~~~~~~~~~~~~~~~~~~~~~~~
onig_stubs.c:162:34: warning: passing 'OnigUChar [90]' to parameter of type 'const char *' converts between pointers to integer types with different sign [-Wpointer-sign]
        error = caml_copy_string(err_buf);
                                 ^~~~~~~
/Users/philippe/.opam/ouaibedev/lib/ocaml/caml/alloc.h:39:48: note: passing argument to parameter here
CAMLextern value caml_copy_string (char const *);
                                               ^
onig_stubs.c:204:18: warning: initializing 'const OnigUChar *' (aka 'const unsigned char *') with an expression of type 'const char *' converts between pointers to integer types with different sign [-Wpointer-sign]
    const UChar* string = String_val(string_val);
                 ^        ~~~~~~~~~~~~~~~~~~~~~~
onig_stubs.c:233:51: warning: passing 'OnigUChar [90]' to parameter of type 'const char *' converts between pointers to integer types with different sign [-Wpointer-sign]
    caml_raise_with_string(*ocaml_onig_Error_exn, err_buf);
                                                  ^~~~~~~
/Users/philippe/.opam/ouaibedev/lib/ocaml/caml/fail.h:93:65: note: passing argument to parameter 'msg' here
CAMLextern void caml_raise_with_string (value tag, char const * msg)
                                                                ^
onig_stubs.c:246:18: warning: initializing 'const OnigUChar *' (aka 'const unsigned char *') with an expression of type 'const char *' converts between pointers to integer types with different sign [-Wpointer-sign]
    const UChar* string = String_val(string_val);
                 ^        ~~~~~~~~~~~~~~~~~~~~~~
onig_stubs.c:273:51: warning: passing 'OnigUChar [90]' to parameter of type 'const char *' converts between pointers to integer types with different sign [-Wpointer-sign]
    caml_raise_with_string(*ocaml_onig_Error_exn, err_buf);
                                                  ^~~~~~~
/Users/philippe/.opam/ouaibedev/lib/ocaml/caml/fail.h:93:65: note: passing argument to parameter 'msg' here
CAMLextern void caml_raise_with_string (value tag, char const * msg)
                                                                ^
6 warnings generated.
  ocamlmklib src/dlloniguruma_stubs.so,src/liboniguruma_stubs.a
ld: warning: dylib (/opt/local/lib/libonig.dylib) was built for newer macOS version (11.2) than being linked (11.0)
    ocamlopt src/oniguruma.cmxs
ld: warning: dylib (/opt/local/lib/libonig.dylib) was built for newer macOS version (11.2) than being linked (11.0)

***@***.***:~/Sources/Build/ocaml-oniguruma-git$ gcc -v
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/4.2.1
Apple clang version 12.0.5 (clang-1205.0.22.11)
Target: x86_64-apple-darwin20.5.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

***@***.***:~/Sources/Build/ocaml-oniguruma-git$ cc -v
Apple clang version 12.0.5 (clang-1205.0.22.11)
Target: x86_64-apple-darwin20.5.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin


--
Philippe Strauss
Strauss Engineering
CH-1273 Arzier
https://www.strauss-engineering.ch
+41 79 302 28 87

**Comment by alan-j-hu** [comment]
Thank you, I read the error message more carefully and see the problem. Oniguruma uses `const UChar*` (AKA `const unsigned char*`) for its strings, while OCaml uses `const char*`, which are signed chars. I added explicit casts between them.

Could you please checkout the latest `build` branch and see if the warnings are fixed?

**Comment by ghost** [comment]
Still 6 warnings but different ones:

***@***.***:~/Sources/Build/ocaml-oniguruma-git$ git checkout build
Previous HEAD position was e209ef5 Use dune-configurator to find flags for Oniguruma (fixes #1)
Switched to branch 'build'
Your branch is up to date with 'origin/build'.
***@***.***:~/Sources/Build/ocaml-oniguruma-git$ dune clean
***@***.***:~/Sources/Build/ocaml-oniguruma-git$ dune build @install
          cc src/onig_stubs.o
onig_stubs.c:146:24: warning: initializing 'const OnigUChar *const' (aka 'const unsigned char *const') with an expression of type 'const char *' converts between pointers to integer types with different sign [-Wpointer-sign]
    const UChar* const pattern = String_val(pattern_val);
                       ^         ~~~~~~~~~~~~~~~~~~~~~~~
onig_stubs.c:162:34: warning: passing 'OnigUChar [90]' to parameter of type 'const char *' converts between pointers to integer types with different sign [-Wpointer-sign]
        error = caml_copy_string(err_buf);
                                 ^~~~~~~
/Users/philippe/.opam/ouaibedev/lib/ocaml/caml/alloc.h:39:48: note: passing argument to parameter here
CAMLextern value caml_copy_string (char const *);
                                               ^
onig_stubs.c:204:24: warning: initializing 'const OnigUChar *const' (aka 'const unsigned char *const') with an expression of type 'const char *' converts between pointers to integer types with different sign [-Wpointer-sign]
    const UChar* const string = String_val(string_val);
                       ^        ~~~~~~~~~~~~~~~~~~~~~~
onig_stubs.c:227:55: warning: passing 'OnigUChar [90]' to parameter of type 'const char *' converts between pointers to integer types with different sign [-Wpointer-sign]
        caml_raise_with_string(*ocaml_onig_Error_exn, err_buf);
                                                      ^~~~~~~
/Users/philippe/.opam/ouaibedev/lib/ocaml/caml/fail.h:93:65: note: passing argument to parameter 'msg' here
CAMLextern void caml_raise_with_string (value tag, char const * msg)
                                                                ^
onig_stubs.c:246:24: warning: initializing 'const OnigUChar *const' (aka 'const unsigned char *const') with an expression of type 'const char *' converts between pointers to integer types with different sign [-Wpointer-sign]
    const UChar* const string = String_val(string_val);
                       ^        ~~~~~~~~~~~~~~~~~~~~~~
onig_stubs.c:267:55: warning: passing 'OnigUChar [90]' to parameter of type 'const char *' converts between pointers to integer types with different sign [-Wpointer-sign]
        caml_raise_with_string(*ocaml_onig_Error_exn, err_buf);
                                                      ^~~~~~~
/Users/philippe/.opam/ouaibedev/lib/ocaml/caml/fail.h:93:65: note: passing argument to parameter 'msg' here
CAMLextern void caml_raise_with_string (value tag, char const * msg)
                                                                ^
6 warnings generated.
  ocamlmklib src/dlloniguruma_stubs.so,src/liboniguruma_stubs.a
ld: warning: dylib (/opt/local/lib/libonig.dylib) was built for newer macOS version (11.2) than being linked (11.0)
    ocamlopt src/oniguruma.cmxs
ld: warning: dylib (/opt/local/lib/libonig.dylib) was built for newer macOS version (11.2) than being linked (11.0)
***@***.***:~/Sources/Build/ocaml-oniguruma-git$ 

> Le 27 août 2021 à 18:08, Alan ***@***.***> a écrit :
> 
> 
> Thank you, I read the error message more carefully and see the problem. Oniguruma uses const UChar* (AKA const unsigned char*) for its strings, while OCaml uses const char*, which are signed chars. I added explicit casts between them.
> 
> Could you please checkout the latest build branch and see if the warnings are fixed?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android. 
> 

--
Philippe Strauss
Strauss Engineering
CH-1273 Arzier
https://www.strauss-engineering.ch
+41 79 302 28 87

**Comment by alan-j-hu** [comment]
Are you sure you have the latest commit to `build`? The code snippets in your compiler warnings don't contain the casts that I added.

**Comment by ghost** [comment]
OOPS sorry I forgot to git pull

Yes the warnings are GONE!

Thank you!

> Le 27 août 2021 à 18:30, Alan ***@***.***> a écrit :
> 
> 
> Are you sure you have the latest commit to build? The code snippets in your compiler warnings don't contain the casts that I added.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android. 
> 

--
We'll never be royals
It don't run in our blood
That kind of luxe just ain't for us
We crave a different kind of buzz
And we aren't caught up in your love affair
      -- Lorde
